- name: Using default deploy method
  community.docker.docker_stack:
    state: present
    name: keycloak
    resolve_image: always
    compose:
      - "{{ role_path }}/files/docker-compose.yaml"
  environment:
    ADMIN_PASSWORD: "{{ service.admin_password }}"
    DB_PASSWORD: "{{ service.database.password }}"
    DB_INIT: "{{ service.database.init }}"
    BASE_PATH: "{{ role_path }}"
