version: "3.8"
services:
  onlyoffice-document-server:
    hostname: onlyoffice-document-server
    image: onlyoffice/documentserver:latest
    environment:
      - JWT_SECRET=${ONLYOFFICE_JWT_SECRET}
    ports:
      - 9000:80
    volumes:
      - config:/etc/onlyoffice/documentserver
      - data:/var/www/onlyoffice/Data
      - log:/var/log/onlyoffice
      - fonts:/usr/share/fonts/truetype/custom
      - lib:/var/lib/onlyoffice
      - psql:/var/lib/postgresql
      - rabbit:/var/lib/rabbitmq
      - redis:/var/lib/redis

volumes:
  config:
  data:
  log:
  fonts:
  lib:
  psql:
  rabbit:
  redis:
