- name: Initialize server
  hosts: clic
  tasks:
    - name: Install required packages
      ansible.builtin.apt:
        update_cache: true
        pkg:
          - ansible # Required for ansible-pull
          - borgbackup # Required since we need borg CLI to init repository
          - docker.io # Required for docker
          - python3-docker # Required for docker
          - python3-jsondiff # Required for docker

    - name: Install required roles and collections
      ansible.builtin.command:
        argv:
          - ansible-galaxy
          - install
          - roles
          - hifis.unattended_upgrades
          - borgbase.ansible_role_borgbackup
      changed_when: true

    - name: Get docker path
      ansible.builtin.command: which docker
      ignore_errors: true
      changed_when: true
      register: docker_path

    - name: Create cron job to prune unused Docker images, containers and networks weekly
      ansible.builtin.cron:
        name: "Prune Docker images weekly"
        minute: "0"
        hour: "0"
        day: "*"
        weekday: "0"
        job: "{{ docker_path.stdout }} system prune -af"
