- name: Using default deploy method
  community.docker.docker_stack:
    state: present
    name: qrbill-generator
    resolve_image: always
    compose:
      - "{{ role_path }}/files/docker-compose.yaml"
