argument_specs:
  main:
    options:
      service:
        type: "dict"
        required: true
        options:
          secrets_file:
            required: true
          user:
            required: true
          repository:
            required: true
          github:
            type: "dict"
            required: true
            options:
              secret:
                required: true
              access_token:
                required: true
              assignees:
                required: true
