- name: Using default deploy method
  community.docker.docker_stack:
    state: present
    name: bookstack
    resolve_image: always
    compose:
      - "{{ role_path }}/files/docker-compose.yaml"
  environment:
    DATABASE_PASSWORD: "{{ service.database.password }}"
    DATABASE_INIT: "{{ service.database.init }}"
    SMTP_IT_PASSWORD: "{{ general.mail.it_password }}"
