- name: Using default deploy method
  community.docker.docker_stack:
    state: present
    name: directus
    resolve_image: always
    compose:
      - ../directus/docker-compose.yaml
  environment:
    DIRECTUS_ADMIN_PASSWORD: "{{ DIRECTUS_ADMIN_PASSWORD }}"
    DIRECTUS_KEYCLOAK_SECRET: "{{ DIRECTUS_KEYCLOAK_SECRET }}"
    DIRECTUS_SECRET: "{{ DIRECTUS_SECRET }}"
    DIRECTUS_KEY: "{{ DIRECTUS_KEY }}"
    DIRECTUS_DATABASE_INIT: "{{ DIRECTUS_DATABASE_INIT }}"
    DIRECTUS_DATABASE_PASSWORD: "{{ DIRECTUS_DATABASE_PASSWORD }}"
    SMTP_IT_PASSWORD: "{{ SMTP_IT_PASSWORD }}"

- name: Wait for directus to be available
  ansible.builtin.wait_for:
    port: 8001

- name: Get container id
  ansible.builtin.command:
    cmd: docker service ps directus_directus --filter desired-state=running -q
  register: ps

- name: Compute container name
  ansible.builtin.set_fact:
    container_name: directus_directus.1.{{ ps.stdout }}

- name: Copy schema into container
  community.docker.docker_container_copy_into:
    container: "{{ container_name }}"
    container_path: /snapshot.yaml
    path: ../directus/snapshot.yaml

- name: Apply schema
  community.docker.docker_container_exec:
    container: "{{ container_name }}"
    command: npx directus schema apply /snapshot.yaml -y
