- name: Using default deploy method
  community.docker.docker_stack:
    state: present
    name: clicketing
    resolve_image: always
    compose:
      - "{{ role_path }}/files/docker-compose.yaml"
  environment:
    DIRECTUS_TOKEN: "{{ service.directus_token }}"
