- name: Deploy Caddy reverse proxy
  hosts: localhost
  connection: local
  become: true
  tasks:
    - name: Install required packages
      ansible.builtin.apt:
        update_cache: true
        pkg:
          - debian-keyring
          - debian-archive-keyring
          - apt-transport-https
          - curl

    - name: Update keyring
      ansible.builtin.shell: curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/gpg.key' | gpg --dearmor -o /usr/share/keyrings/caddy-stable-archive-keyring.gpg
      changed_when: true

    - name: Update mirror list
      ansible.builtin.shell: curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt' | sudo tee /etc/apt/sources.list.d/caddy-stable.list
      changed_when: true

    - name: Install caddy
      ansible.builtin.apt:
        update_cache: true
        pkg:
          - caddy

    - name: Setup Caddyfile
      ansible.builtin.copy:
        src: ../caddy/Caddyfile
        dest: /etc/caddy/Caddyfile
        mode: "740"

    - name: Reload Caddyfile
      ansible.builtin.command: caddy reload --config /etc/caddy/Caddyfile
      changed_when: true
