- name: Apply directus snapshot
  hosts: localhost
  tasks:
    - name: Get directus schema
      ansible.builtin.get_url:
        url: "{{ SNAPSHOT_URL }}"
        dest: /tmp/directus_snapshot.yaml
        mode: "0755"

    - name: Retrieve directus container id
      ansible.builtin.command:
        cmd: docker ps -f status=running -f expose=8055 -q
      register: container
      changed_when: false

    - name: Copy snapshot to directus container
      community.docker.docker_container_copy_into:
        container: "{{ container.stdout }}"
        path: /tmp/directus_snapshot.yaml
        container_path: /snapshot.yaml

    - name: Apply directus snapshot
      community.docker.docker_container_exec:
        container: "{{ container.stdout }}"
        command: npx directus schema apply /snapshot.yaml
